// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextHoliday.Infrastructure.Persistence;

#nullable disable

namespace NextHoliday.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260622194748_SeedCountries")]
    partial class SeedCountries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Continent")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresVisa")
                        .HasColumnType("bit");

                    b.HasKey("Code");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Code = "AF",
                            Capital = "Kabul",
                            Continent = 3,
                            Currency = "AFN",
                            Language = "Pashto",
                            Name = "Afghanistan",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "AL",
                            Capital = "Tirana",
                            Continent = 4,
                            Currency = "ALL",
                            Language = "Albanian",
                            Name = "Albania",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "DZ",
                            Capital = "Algiers",
                            Continent = 1,
                            Currency = "DZD",
                            Language = "Arabic",
                            Name = "Algeria",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "AD",
                            Capital = "Andorra la Vella",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Catalan",
                            Name = "Andorra",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "AO",
                            Capital = "Luanda",
                            Continent = 1,
                            Currency = "AOA",
                            Language = "Portuguese",
                            Name = "Angola",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "AR",
                            Capital = "Buenos Aires",
                            Continent = 7,
                            Currency = "ARS",
                            Language = "Spanish",
                            Name = "Argentina",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "AU",
                            Capital = "Canberra",
                            Continent = 6,
                            Currency = "AUD",
                            Language = "English",
                            Name = "Australia",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "AT",
                            Capital = "Vienna",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "German",
                            Name = "Austria",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "BE",
                            Capital = "Brussels",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Dutch, French, German",
                            Name = "Belgium",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "BO",
                            Capital = "Sucre",
                            Continent = 7,
                            Currency = "BOB",
                            Language = "Spanish, Quechua, Aymara",
                            Name = "Bolivia",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "BR",
                            Capital = "Brasília",
                            Continent = 7,
                            Currency = "BRL",
                            Language = "Portuguese",
                            Name = "Brazil",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "BG",
                            Capital = "Sofia",
                            Continent = 4,
                            Currency = "BGN",
                            Language = "Bulgarian",
                            Name = "Bulgaria",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "CA",
                            Capital = "Ottawa",
                            Continent = 5,
                            Currency = "CAD",
                            Language = "English, French",
                            Name = "Canada",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "CL",
                            Capital = "Santiago",
                            Continent = 7,
                            Currency = "CLP",
                            Language = "Spanish",
                            Name = "Chile",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "CN",
                            Capital = "Beijing",
                            Continent = 3,
                            Currency = "CNY",
                            Language = "Mandarin",
                            Name = "China",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "CO",
                            Capital = "Bogotá",
                            Continent = 7,
                            Currency = "COP",
                            Language = "Spanish",
                            Name = "Colombia",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "CR",
                            Capital = "San José",
                            Continent = 5,
                            Currency = "CRC",
                            Language = "Spanish",
                            Name = "Costa Rica",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "HR",
                            Capital = "Zagreb",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Croatian",
                            Name = "Croatia",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "CU",
                            Capital = "Havana",
                            Continent = 5,
                            Currency = "CUP",
                            Language = "Spanish",
                            Name = "Cuba",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "CY",
                            Capital = "Nicosia",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Greek, Turkish",
                            Name = "Cyprus",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "CZ",
                            Capital = "Prague",
                            Continent = 4,
                            Currency = "CZK",
                            Language = "Czech",
                            Name = "Czech Republic",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "DK",
                            Capital = "Copenhagen",
                            Continent = 4,
                            Currency = "DKK",
                            Language = "Danish",
                            Name = "Denmark",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "DO",
                            Capital = "Santo Domingo",
                            Continent = 5,
                            Currency = "DOP",
                            Language = "Spanish",
                            Name = "Dominican Republic",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "EC",
                            Capital = "Quito",
                            Continent = 7,
                            Currency = "USD",
                            Language = "Spanish",
                            Name = "Ecuador",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "EG",
                            Capital = "Cairo",
                            Continent = 1,
                            Currency = "EGP",
                            Language = "Arabic",
                            Name = "Egypt",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "EE",
                            Capital = "Tallinn",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Estonian",
                            Name = "Estonia",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "FI",
                            Capital = "Helsinki",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Finnish, Swedish",
                            Name = "Finland",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "FR",
                            Capital = "Paris",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "French",
                            Name = "France",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "DE",
                            Capital = "Berlin",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "German",
                            Name = "Germany",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "GR",
                            Capital = "Athens",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Greek",
                            Name = "Greece",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "HU",
                            Capital = "Budapest",
                            Continent = 4,
                            Currency = "HUF",
                            Language = "Hungarian",
                            Name = "Hungary",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "IS",
                            Capital = "Reykjavik",
                            Continent = 4,
                            Currency = "ISK",
                            Language = "Icelandic",
                            Name = "Iceland",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "IN",
                            Capital = "New Delhi",
                            Continent = 3,
                            Currency = "INR",
                            Language = "Hindi, English",
                            Name = "India",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "ID",
                            Capital = "Jakarta",
                            Continent = 3,
                            Currency = "IDR",
                            Language = "Indonesian",
                            Name = "Indonesia",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "IE",
                            Capital = "Dublin",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Irish, English",
                            Name = "Ireland",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "IL",
                            Capital = "Jerusalem",
                            Continent = 3,
                            Currency = "ILS",
                            Language = "Hebrew",
                            Name = "Israel",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "IT",
                            Capital = "Rome",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Italian",
                            Name = "Italy",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "JM",
                            Capital = "Kingston",
                            Continent = 5,
                            Currency = "JMD",
                            Language = "English",
                            Name = "Jamaica",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "JP",
                            Capital = "Tokyo",
                            Continent = 3,
                            Currency = "JPY",
                            Language = "Japanese",
                            Name = "Japan",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "JO",
                            Capital = "Amman",
                            Continent = 3,
                            Currency = "JOD",
                            Language = "Arabic",
                            Name = "Jordan",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "KE",
                            Capital = "Nairobi",
                            Continent = 1,
                            Currency = "KES",
                            Language = "Swahili, English",
                            Name = "Kenya",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "KR",
                            Capital = "Seoul",
                            Continent = 3,
                            Currency = "KRW",
                            Language = "Korean",
                            Name = "South Korea",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "LV",
                            Capital = "Riga",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Latvian",
                            Name = "Latvia",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "LB",
                            Capital = "Beirut",
                            Continent = 3,
                            Currency = "LBP",
                            Language = "Arabic",
                            Name = "Lebanon",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "LT",
                            Capital = "Vilnius",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Lithuanian",
                            Name = "Lithuania",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "LU",
                            Capital = "Luxembourg City",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Luxembourgish, French, German",
                            Name = "Luxembourg",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "MY",
                            Capital = "Kuala Lumpur",
                            Continent = 3,
                            Currency = "MYR",
                            Language = "Malay",
                            Name = "Malaysia",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "MV",
                            Capital = "Malé",
                            Continent = 3,
                            Currency = "MVR",
                            Language = "Dhivehi",
                            Name = "Maldives",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "MT",
                            Capital = "Valletta",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Maltese, English",
                            Name = "Malta",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "MX",
                            Capital = "Mexico City",
                            Continent = 5,
                            Currency = "MXN",
                            Language = "Spanish",
                            Name = "Mexico",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "MC",
                            Capital = "Monaco",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "French",
                            Name = "Monaco",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "MA",
                            Capital = "Rabat",
                            Continent = 1,
                            Currency = "MAD",
                            Language = "Arabic, Berber",
                            Name = "Morocco",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "NL",
                            Capital = "Amsterdam",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Dutch",
                            Name = "Netherlands",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "NZ",
                            Capital = "Wellington",
                            Continent = 6,
                            Currency = "NZD",
                            Language = "English, Maori",
                            Name = "New Zealand",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "NO",
                            Capital = "Oslo",
                            Continent = 4,
                            Currency = "NOK",
                            Language = "Norwegian",
                            Name = "Norway",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "PA",
                            Capital = "Panama City",
                            Continent = 5,
                            Currency = "PAB",
                            Language = "Spanish",
                            Name = "Panama",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "PY",
                            Capital = "Asunción",
                            Continent = 7,
                            Currency = "PYG",
                            Language = "Spanish, Guarani",
                            Name = "Paraguay",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "PE",
                            Capital = "Lima",
                            Continent = 7,
                            Currency = "PEN",
                            Language = "Spanish",
                            Name = "Peru",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "PH",
                            Capital = "Manila",
                            Continent = 3,
                            Currency = "PHP",
                            Language = "Filipino, English",
                            Name = "Philippines",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "PL",
                            Capital = "Warsaw",
                            Continent = 4,
                            Currency = "PLN",
                            Language = "Polish",
                            Name = "Poland",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "PT",
                            Capital = "Lisboa",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Portuguese",
                            Name = "Portugal",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "QA",
                            Capital = "Doha",
                            Continent = 3,
                            Currency = "QAR",
                            Language = "Arabic",
                            Name = "Qatar",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "RO",
                            Capital = "Bucharest",
                            Continent = 4,
                            Currency = "RON",
                            Language = "Romanian",
                            Name = "Romania",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "RU",
                            Capital = "Moscow",
                            Continent = 4,
                            Currency = "RUB",
                            Language = "Russian",
                            Name = "Russia",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "SA",
                            Capital = "Riyadh",
                            Continent = 3,
                            Currency = "SAR",
                            Language = "Arabic",
                            Name = "Saudi Arabia",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "SG",
                            Capital = "Singapore",
                            Continent = 3,
                            Currency = "SGD",
                            Language = "English, Malay, Mandarin, Tamil",
                            Name = "Singapore",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "SK",
                            Capital = "Bratislava",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Slovak",
                            Name = "Slovakia",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "SI",
                            Capital = "Ljubljana",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Slovene",
                            Name = "Slovenia",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "ZA",
                            Capital = "Pretoria",
                            Continent = 1,
                            Currency = "ZAR",
                            Language = "Afrikaans, English, etc.",
                            Name = "South Africa",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "ES",
                            Capital = "Madrid",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Spanish",
                            Name = "Spain",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "LK",
                            Capital = "Colombo",
                            Continent = 3,
                            Currency = "LKR",
                            Language = "Sinhala, Tamil",
                            Name = "Sri Lanka",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "SE",
                            Capital = "Stockholm",
                            Continent = 4,
                            Currency = "SEK",
                            Language = "Swedish",
                            Name = "Sweden",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "CH",
                            Capital = "Bern",
                            Continent = 4,
                            Currency = "CHF",
                            Language = "German, French, Italian, Romansh",
                            Name = "Switzerland",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "TH",
                            Capital = "Bangkok",
                            Continent = 3,
                            Currency = "THB",
                            Language = "Thai",
                            Name = "Thailand",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "TN",
                            Capital = "Tunis",
                            Continent = 1,
                            Currency = "TND",
                            Language = "Arabic",
                            Name = "Tunisia",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "TR",
                            Capital = "Ankara",
                            Continent = 4,
                            Currency = "TRY",
                            Language = "Turkish",
                            Name = "Turkey",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "UA",
                            Capital = "Kyiv",
                            Continent = 4,
                            Currency = "UAH",
                            Language = "Ukrainian",
                            Name = "Ukraine",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "AE",
                            Capital = "Abu Dhabi",
                            Continent = 3,
                            Currency = "AED",
                            Language = "Arabic",
                            Name = "United Arab Emirates",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "GB",
                            Capital = "London",
                            Continent = 4,
                            Currency = "GBP",
                            Language = "English",
                            Name = "United Kingdom",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "US",
                            Capital = "Washington D.C.",
                            Continent = 5,
                            Currency = "USD",
                            Language = "English",
                            Name = "United States",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "UY",
                            Capital = "Montevideo",
                            Continent = 7,
                            Currency = "UYU",
                            Language = "Spanish",
                            Name = "Uruguay",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "VA",
                            Capital = "Vatican City",
                            Continent = 4,
                            Currency = "EUR",
                            Language = "Italian, Latin",
                            Name = "Vatican City",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "VE",
                            Capital = "Caracas",
                            Continent = 7,
                            Currency = "VES",
                            Language = "Spanish",
                            Name = "Venezuela",
                            RequiresVisa = true
                        },
                        new
                        {
                            Code = "VN",
                            Capital = "Hanoi",
                            Continent = 3,
                            Currency = "VND",
                            Language = "Vietnamese",
                            Name = "Vietnam",
                            RequiresVisa = true
                        });
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nchar(2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.History.ClimateHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AverageTemperature")
                        .HasColumnType("float");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<double>("RainProbability")
                        .HasColumnType("float");

                    b.Property<string>("WeatherCondition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("ClimateHistories");
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.History.PriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EstimatedFlightPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedHotelPricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.Destination", b =>
                {
                    b.HasOne("NextHoliday.Domain.Entities.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.History.ClimateHistory", b =>
                {
                    b.HasOne("NextHoliday.Domain.Entities.Destination", "Destination")
                        .WithMany("ClimateHistories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.History.PriceHistory", b =>
                {
                    b.HasOne("NextHoliday.Domain.Entities.Destination", "Destination")
                        .WithMany("PriceHistories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.Country", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.Destination", b =>
                {
                    b.Navigation("ClimateHistories");

                    b.Navigation("PriceHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
