// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextHoliday.Infrastructure.Persistence;

#nullable disable

namespace NextHoliday.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260619125918_AddDescriptionToDestination")]
    partial class AddDescriptionToDestination
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NextHoliday.Domain.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Continent")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresVisa")
                        .HasColumnType("bit");

                    b.HasKey("Code");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Code = "PT",
                            Capital = "",
                            Continent = 4,
                            Currency = "",
                            Language = "",
                            Name = "Portugal",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "ES",
                            Capital = "",
                            Continent = 4,
                            Currency = "",
                            Language = "",
                            Name = "Spain",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "FR",
                            Capital = "",
                            Continent = 4,
                            Currency = "",
                            Language = "",
                            Name = "France",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "IT",
                            Capital = "",
                            Continent = 4,
                            Currency = "",
                            Language = "",
                            Name = "Italy",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "US",
                            Capital = "",
                            Continent = 5,
                            Currency = "",
                            Language = "",
                            Name = "United States",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "JP",
                            Capital = "",
                            Continent = 3,
                            Currency = "",
                            Language = "",
                            Name = "Japan",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "CN",
                            Capital = "",
                            Continent = 3,
                            Currency = "",
                            Language = "",
                            Name = "China",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "BR",
                            Capital = "",
                            Continent = 7,
                            Currency = "",
                            Language = "",
                            Name = "Brazil",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "EG",
                            Capital = "",
                            Continent = 1,
                            Currency = "",
                            Language = "",
                            Name = "Egypt",
                            RequiresVisa = false
                        },
                        new
                        {
                            Code = "AU",
                            Capital = "",
                            Continent = 6,
                            Currency = "",
                            Language = "",
                            Name = "Australia",
                            RequiresVisa = false
                        });
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nchar(2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.History.ClimateHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AverageTemperature")
                        .HasColumnType("float");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<double>("RainProbability")
                        .HasColumnType("float");

                    b.Property<string>("WeatherCondition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("ClimateHistories");
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.History.PriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EstimatedFlightPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedHotelPricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.Destination", b =>
                {
                    b.HasOne("NextHoliday.Domain.Entities.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.History.ClimateHistory", b =>
                {
                    b.HasOne("NextHoliday.Domain.Entities.Destination", "Destination")
                        .WithMany("ClimateHistories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.History.PriceHistory", b =>
                {
                    b.HasOne("NextHoliday.Domain.Entities.Destination", "Destination")
                        .WithMany("PriceHistories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.Country", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("NextHoliday.Domain.Entities.Destination", b =>
                {
                    b.Navigation("ClimateHistories");

                    b.Navigation("PriceHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
